language: node_js
node_js:
- 6
script:
- npm test
- npm run deploy
after_success:
- npm run docs
- chmod +x ./docs.sh
- ./docs.sh
branches:
  only:
  - master
notifications:
  email: false
  slack: the-tricktionary:VdZSlFi4J1AHCcQY96RU5dDZ
